language: php
php:
- 5.4
- 5.5
- 5.6
env:
- DB=mysql
before_script:
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS snipeit_laravel;"
  -utravis; fi
- curl -s http://getcomposer.org/installer | php
- cp app/config/production/database.example.php app/config/database.php
- cp app/config/production/mail.example.php app/config/mail.php
- php composer.phar self-update
- php composer.phar install --prefer-source --no-interaction --dev
- php artisan key:generate
- php artisan migrate:install
- php artisan migrate --package cartalyst/sentry
- php artisan migrate
- php artisan db:seed
script: phpunit
notifications:
  slack:
    secure: vv9we1RxB9RsrMbomSdq6D7vz/okobw87pEkgIZjB+hj1QpQ2by90gsPsOa+NgsJEFaEP7e4KlT6SH8kK+zhbmuKaUd3d1//XdcancE22LZXi6tkiB5yuR/Jhhb1LLDqyGJTB4D92hMnnCPiUjpxNA3r437ttNeYRdYIEEP3drA=
